# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1adcc07724fa8452218333af3811afc890b613edadbf7db510a111c7cdf07e4ab7763736573d65927e91537923c19d52137ca39ab45e2e982d36e2eccd6a7906

test:
  secret_key_base: 4b4c0ba7e6a8b15fe1597338672180a85f31540fb2138c486db23d9de9007709d45616653633cbd8d43a2077771640f533bc6350b838d7792435548882d673fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
